name: Build and test on PRs
on: pull_request

jobs:
  gradle:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Build
        run: firebase emulators:exec --project my-firebase-project --import=src/test/resources/firebase_data './gradlew build'
